version: '3'
services:
  php:
    container_name: php-apache-1
    #image: php:7.3-apache
    build: .
    volumes:
      - ./php:/var/wwww/html/
    ports:
      - 8000:80
    depends_on:
      - db
  db:
    container_name: mysql
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABAST: db_test
      MYSQL_USER: mysql
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"


  

